name: Scan Cameras

on:
  workflow_dispatch:  # permite rodar manualmente
  schedule:
    - cron: "0 * * * *"  # opcional: roda 1x por hora (horário UTC)

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      CAMERA_USER: ${{ secrets.CAMERA_USER }}
      CAMERA_PASS: ${{ secrets.CAMERA_PASS }}
      CAMERA_ID_START: "1000"
      CAMERA_ID_END: "1100"
      REQUEST_TIMEOUT: "3"
      REQUEST_SLEEP: "0.2"
      # Exemplo de câmeras extras: "1070 - MALIBU HOME - 12,Portao,Garagem"
      EXTRA_CAMERAS: "1070 - MALIBU HOME - 12"

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Rodar varredura de câmeras
        run: |
          python scan_cameras.py